version: '3.7'
services:
  backend-dev:
    image: erasme/ws25-culture-du-risque-db:latest
    build: db/
    ports:
      - "8090:8090"
    volumes:
      - ./db/pb_migrations/:/pb_migrations
      - ./db/pb_data/:/pb_data/
  frontend-dev:
    image: erasme/ws25-culture-du-risque-front:latest
    build: 
      context: front/
    volumes:
      - ./front/src/:/app/src
    ports:
      - "5173:5173" #keep same port to avoid Cross scripting errors
    env_file:
      - .env